### PR TITLE
Allow to have both Rails and Rage controllers in one application

### PR DESCRIPTION
**Pull request by rsamoilov**

### CODE REVIEW

**Comment by efibootmgr** [comment]
I came across a problem actually, because RageController doesn't support any gems that patch Rails controller. Like serializer gems that allow you to write something like
render json: Model, serializer: ModelSerializer
The RageController does not get those features.

**Comment by rsamoilov** [comment]
huh, that's an interesting point. Are you talking about ActiveModelSerializers?

In general, given how Rage and Rails are different internally, I am not sure it would be possible to patch Rails controllers. My expectation is that gem maintainers would need to update their code to patch Rage controllers too.

**Comment by efibootmgr** [comment]
Thanks for reply, i think so. It's not critical, experienced developer can add features like that manually to rage controllers of course, if really needed. Just wanted to point to one downside/problem of using Rage and Rails together.
I was also having problems with **rage console** command, when triyng to use it in rage + rails template. Using any sql queries results in
`No connection pool for 'ActiveRecord::Base' found. (ActiveRecord::ConnectionNotEstablished)`
The **rails console** work properly and gets active record connection from config.

**Comment by rsamoilov** [comment]
Thanks! This should be fixed in #84.

**Pull request merged**
